version: '3'
services:
  app:
    stdin_open: true
    tty: true
    build: .
    command: sh -c "npm run migration && npm run dev"
    ports:
      - 3003:3003
    volumes:
      - .:/home/app
      - logvolume01:/var/log
    depends_on:
      - postgres
  postgres:
    image: 'postgres:9.6-alpine'
    env_file: ormconfig.env
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  nginx:
    image: nginx:stable-alpine
    ports:
      - '4000:4000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
volumes:
  logvolume01: {}
  database: {}
